<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>

<body>
    <script>

        const promise = new Promise((resolve, reject) => {
            setTimeout(() => {
                console.log('once')
                resolve('success')
            }, 1000)
        })

        const start = Date.now()

        promise.then((res) => {
            console.log(res, Date.now() - start)
        })

        promise.then((res) => {
            console.log(res, Date.now() - start)
        })

    </script>

    运行结果：

    once

    success 1005
    
    success 1007

    解释：promise 的 .then 或者 .catch 可以被调用多次，但这里 Promise 构造函数只执行一次。

    或者说 promise 内部状态一经改变，并且有了一个值，那么后续每次调用 .then 或者 .catch 都会直接拿到该值。


</body>

</html>
